FROM cr.loongnix.cn/loongson/loongnix:20
MAINTAINER qiangxuhui@loongson.cn

ENV PARAMS=""

ENV TZ=PRC

RUN apt update -y && apt install openjdk-8-jre -y

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD target/xxl-job-admin-*.jar /app.jar

ENTRYPOINT ["sh","-c","java -jar $JAVA_OPTS /app.jar $PARAMS"]
